name: Good_job CD

# main branch에 push 되면 실행
on:
  pull_request:
    branches:
      - main
jobs:
  deploy:
    name: CD Pipeline
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: ['16.x']
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: 43.200.3.250
          username: ubuntu
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/goodjob_BE
            sudo git pull
            sudo npm update
            sudo npm ci
            sudo npm run start
