name: Good_job CD

# main branch에 push 되면 실행
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: CD Pipeline
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: ['14.x']
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_USERNAME }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            cd /home/ubuntu/goodjob_BE
            sudo git pull origin main
            sudo npm ci
            sudo pm2 stop 0
            sudo pm2 kill
            sudo npm run start
