name: Good_job CD

# main branch에 push 되면 실행
on:
  pull_request:
    branches:
      - main
jobs:
  deploy:
    name: CD Pipeline
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: ['16.13.1']
    steps:
      - name: Checkout sorce code.
        uses: actions/checkout@v2
      - name: Create env file
        run: |
          touch .env
          cat << EOF >> .env
          ${{ secrets.GOODJOB_SECRET }}
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Install AWS CLI 2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          which aws
          sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Generate deployment package
        run: zip -r goodjob_BE.zip . -x ".git/*" -x ".github/*"
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: good_job_auto
          environment_name: Goodjobauto-env
          region: ${{ secrets.AWS_REGION }}
          version_label: 12346
          deployment_package: goodjob_BE.zip
