
name: Good_job CI

on:
  push:
    branches: [ "sw" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Use Node.js 16.x
          uses: actions/setup-node@v3
          with:
            node-version: 16.x
            cache: 'npm'
        - name: create env file
          working-directory: ../goodjob_BE
          run: |
            touch .env
            cat << EOF >> .env
            ${{ secrets.GOODJOB_SECRET }}
        - name: npm install
          working-directory: ../goodjob_BE
          run: |
            npm install 
        - name: npm test
          working-directory: ../goodjob_BE
          run: |
            npm test
        - name: if fail
          uses: actions/github-script@0.2.0
          with:
            github-token: ${{github.token}}
            script: |
              const ref = "${{github.ref}}"
              const name = ref.split("/")[2]
              console.log(ref)
              await github.pulls.createReview({
              ...context.repo,
              name,
              body:"테스트코드를 다시 확인해주세요. ",
              event: "REQUEST_CHANGES"
              })
              await github.pulls.update({
              ...context.repo,
              name,
              state: "closed"
              })
          if: failure()
        - name: Merge sw -> test
          uses: devmasx/merge-branch@master
          with:
            type: now
            from_branch: sw
            target_branch: test
            github_token: ${{ github.token }}
